// Key map for commands
const keyMap = {
  '[': insertAndEnterBox,
  '(': insertAndEnterCodeBox,
  ']': exitBoxRight,
  ')': exitBoxRight,
  'Ctrl-[': enterNextBox,
  'Ctrl-(': enterNextBox,
  'Ctrl-]': exitBoxLeft,
  'Ctrl-)': exitBoxLeft,
  'Ctrl-f': moveCursorForward,
  'Ctrl-b': moveCursorBackward,
  'Ctrl-a': moveCursorToStartOfLineInBox,
  'Ctrl-Shift-C': shrinkBox,
  'Ctrl-d': deleteCharForward,
  'Delete': deleteCharForward,
  'Ctrl-e': moveCursorToEndOfLineInBox,
  'Ctrl-k': killLine,
  'Ctrl-p': moveCursorUp,
  'Ctrl-n': moveCursorDown,
  'Ctrl-q': insertQuotedChar,
  'Ctrl-x': deleteCurrentBox,	// placeholder
  'Ctrl-y': yank,
  'Ctrl-,': moveCursorToStartOfBox,
  'Ctrl-.': moveCursorToEndOfBox,
  'Ctrl-*': explodeBox,
  'ArrowLeft': moveCursorBackward,
  'ArrowRight': moveCursorForward,
  'ArrowUp': moveCursorUp,
  'ArrowDown': moveCursorDown,
  'Backspace': deleteCharAtCursor,
  'Enter': insertNewline
};
